// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojdvggqzoufgiyfpdvwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZHZnZ3F6b3VmZ2l5ZnBkdndiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDQ0NjgsImV4cCI6MjA3NDIyMDQ2OH0.N5Kih_6mHzW0YLo-UXLizH0o2IQrzb5pXpMRqAKDA5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});